version: '3.4'
#version: '3.7'
volumes:
  kong_data: {}
  users_data: {}
  tais_data: {}

networks: #Red interna para comunicar los servicios (“Services on the same network can communicate with each other using their name”)
  kong-net:

services:
  api-tai:
    image: api-tai-image
    build:
      context: ./apiTAI
      dockerfile: ./Dockerfile
    restart: unless-stopped
    ports:
      - 8082:8082
    networks: # Networks to join
      - kong-net
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://Tais-database:3306/Tais?createDatabaseIfNotExist=true
    depends_on:
      - api-auth
  api-auth:
    image: api-auth-image
    build:
      context: ./apiAuth
      dockerfile: ./Dockerfile
    restart: unless-stopped
    ports:
      - 8081:8081
    networks: # Networks to join
      - kong-net
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://Usuarios-database:3306/Usuarios?createDatabaseIfNotExist=true
    depends_on:
      - users-database
  users-database:
    image: mysql #Usamos imagen del respositorio ya creada
    hostname: Usuarios-database
    cap_add:
      - SYS_NICE
    restart: unless-stopped
    ports:
      - "3307:3306"
    networks:
      - kong-net
    volumes:
      - users_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      #MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: Usuarios
      MYSQL_ROOT_HOST: '%'
    depends_on:
      - tais-database
  tais-database:
    image: mysql #Usamos imagen del respositorio ya creada
    hostname: Tais-database
    cap_add:
      - SYS_NICE
    restart: unless-stopped
    ports:
      - "3308:3306"
    networks:
      - kong-net
    volumes:
      - tais_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      #MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: Tais
      MYSQL_ROOT_HOST: '%'
  client:
    image: myclient-angular-image
    build:
      context: ./myClient
      dockerfile: ./Dockerfile
    restart: unless-stopped
    ports:
      - 80:80
    networks: # Networks to join
      - kong-net
