volumes:
  kong_data: {}
  tais_data: {}

networks:
  kong-net: {}

services:
  api-tai:
    image: api-tai-image
    build:
      context: ./apiTAI
      dockerfile: ./Dockerfile
    restart: always
    ports:
      - 8082:8082
    networks:
      - kong-net
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://tais-database:3306/Tais?createDatabaseIfNotExist=true
    depends_on:
      - tais-database

  tais-database:
    image: mysql:8.0 # Specify MySQL version
    hostname: Tais-database
    cap_add:
      - SYS_NICE
    restart: always
    ports:
      - "3308:3306"
    expose:
      - "3306"
    networks:
      - kong-net
    volumes:
      - tais_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: Tais
      MYSQL_ROOT_HOST: '%'

  client:
    image: myclient-angular-image
    build:
      context: ./myClient
      dockerfile: ./Dockerfile
    restart: always
    ports:
      - 80:80
    networks:
      - kong-net